import { Header } from "@/components/Header";
import Head from "next/head";
import Link from "next/link";
import { Star } from "phosphor-react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nerdzão Day | Início</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <section className="bg-banner min-h-screen pt-24 bg-fixed flex flex-col items-center justify-center">
        <span className="bg-gray-800 text-white px-4 py-2 rounded-full flex items-center justify-center gap-2">
          <Star size={19} weight="fill" />
          Exclusivo
        </span>

        <h1 className="text-pink-500 text-5xl md:text-6xl lg:text-7xl font-bold mt-7">
          Nerdzão Day
        </h1>
        <h2 className="text-white text-5xl md:text-6xl lg:text-7xl mt-5 font-bold">
          Super edição 2023
        </h2>

        <p className="text-white mt-10 text-xl max-w-sm md:text-2xl md:max-w-md text-center font-light">
          Está chegando a hora de um dos eventos mais incríveis!
        </p>

        <Link href="/incrições">
          <div className="mt-14 bg-gray-800 text-white px-6 py-3 rounded-full animate-bounce hover:ring-4 hover:ring-pink-500 transition-all">
            Increver-se agora
          </div>
        </Link>
      </section>

      <div className="bg-gradient-to-r from-pink-500 to-purple-500 max-w-6xl mx-auto w-full h-10 relative -top-5 rounded-full " />

      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
    </>
  );
}
